#!bin/bash
echo ich mag fliegen

echo Delic Adrijan ist ein kleiner Hurensohn
echo Delic Adrijan ist ein kleiner Hurensohn 
echo Delic Adrijan ist ein kleiner Hurensohn
echo Delic Adrijan ist ein kleiner Hurensohn
echo Delic Adrijan ist ein kleiner Hurensohn
echo Delic Adrijan ist ein kleiner Hurensohn
echo Delic Adrijan ist ein kleiner Hurensohn
echo Delic Adrijan ist ein kleiner Hurensohn
echo Delic Adrijan ist ein kleiner Hurensohn







